spring_profiles: postgresql,default
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}/${DB_ENV_DB:postgres}
  username: ${DB_ENV_USER:postgres}
  password: ${DB_ENV_PASS:}

oauth:
  client:
    override: true
  clients:
    user-admin:
      id: user-admin
      secret: admin
      authorized-grant-types: client_credentials
      scope: uaa.none
      authorities: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin
      authorities: uaa.resource,scim.read

scim:
  username_pattern: '[a-z0-9+\-_.@]+'
  users:
    - admin@sequenceiq.com|seqadmin|admin@sequenceiq.com|Default|User|openid,cloudbreak.templates,cloudbreak.blueprints,cloudbreak.credentials,cloudbreak.stacks,sequenceiq.cloudbreak.admin,sequenceiq.cloudbreak.user,sequenceiq.account.abcd1234.SequenceIQ,periscope.cluster,cloudbreak.events,cloudbreak.usages.global,cloudbreak.usages.account,cloudbreak.usages.user,cloudbreak.recipes
