spring_profiles: postgresql,default
database:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://${DB_PORT_5432_TCP_ADDR}:${DB_PORT_5432_TCP_PORT}/${DB_ENV_DB:postgres}
  username: ${DB_ENV_USER:postgres}
  password: ${DB_ENV_PASS:}

oauth:
  client:
    override: true
  clients:
    user-admin:
      id: user-admin
      secret: admin
      authorized-grant-types: client_credentials
      scope: uaa.none
      authorities: uaa.admin,clients.read,clients.write,clients.secret,scim.read,scim.write,clients.admin
      authorities: uaa.resource,scim.read

scim:
  username_pattern: '[a-z0-9+\-_.@]+'
  users:
    - user1|changeMe|user1@home-monitor.io|First|User|uaa.admin
